PORT=10006

HARD_DISK_ONLY=true
NO_DELETE=true

SERVICE_NAME="valkyrie"
ENVIRONMENT="DEVELOPMENT"
LOG_LEVEL="DEBUG"

DB_NAME="valkyrie"
DB_USERNAME="lucas"
DB_PASSWORD="123"
DB_HOSTNAME="localhost"
DB_PORT="5432"

INPUT="/home/pine/bio-input"
OUTPUT="/home/pine/bio-output"
TEMP_UPLOAD="/home/pine/temp"

ACCESS_KEY="minioadmin"
SECRET_KEY="minioadmin"
REGION="us-east-2"
ENDPOINT="localhost:9000"
BUCKET_MAX_SIZE=1024
BUCKET_MAX_COUNT=100000
DELETE_INTERVAL=100
