PORT=10006
JWL_URL="https://genome.vinbigdata.org/user/.well-known/jwks"
ISSUERS=["https://genome.vinbigdata.org/user"]
AUDIENCES=["openid","user"]
PURPOSE="access"

HARD_DISK_ONLY=true
NO_DELETE=true

SERVICE_NAME="valkyrie"
ENVIRONMENT="DEVELOPMENT"
LOG_LEVEL="DEBUG"

DB_NAME="testdb"
DB_USERNAME="testuser"
DB_PASSWORD="testpassword"
DB_HOSTNAME="localhost"
DB_PORT="5432"

INPUT="/home/ubuntu/input"
OUTPUT="/home/ubuntu/output"
TEMP_UPLOAD="/home/ubuntu/temp"

ACCESS_KEY="minioadmin"
SECRET_KEY="minioadmin"
REGION="us-east-2"
ENDPOINT="localhost:9000"
BUCKET_MAX_SIZE=1024
BUCKET_MAX_COUNT=100000
DELETE_INTERVAL=100
