database:
    host: "127.0.0.1"
    port: "5432"
    user: "lucas"
    password: "123"
    dbname: "workflowdb"

server:
    host: "127.0.0.1"
    port: "8084"
    shutdowntimeout: "5"
    loglevel: "debug"
    environment: "production"

valkyrie:
    host:  "http://127.0.0.1" # Should be able to access from the client side
    port:  "10006"
