PORT=10002
ENVIRONMENT="DEVELOPMENT"
LOG_LEVEL="debug"
SERVICE_NAME="executor-1"

FAIL_OVER_TIME = 2
MAX_CONCURRENT_JOB = 1

K8S_CONFIG_FILE="/home/pine/.kube/config"
K8S_NAMESPACE="default"
NODE_NAME="test"
K8S_DELETE_JOB=false
K8S_JOB_TTL_AFTER_FINISHED=120
K8S_MAX_CPU = 1
K8S_MAX_RAM = 1
K8S_NODE_LABEL_KEY = "node-label-key"
K8S_NODE_LABEL_VALUE = "node-label-value"

OUTPUT_DIR_PREFIX = "/home/pine/bio-output"
FUSE_MOUNT_POINT = ""
MINIO_ENDPOINT = ""
